"""P-chains for simplicial homology computations.

This module provides the :class:`PChain` class for representing and
manipulating formal sums of simplices with integer coefficients.

A p-chain is a fundamental algebraic object in simplicial homology theory.
Formally, given a simplicial complex K, the group of p-chains C_p(K) is the
free abelian group generated by the p-simplices of K. Elements are formal
sums of the form ``sum n_s * s`` where s ranges over p-simplices and
n_s is an integer.

References
----------
- Hatcher, A. "Algebraic Topology", Chapter 2.1
- Munkres, J. "Elements of Algebraic Topology", Chapter 1
"""

from __future__ import annotations

from typing import Any


class PChain:
    """A p-chain, i.e., a formal sum of p-simplices with integer coefficients.

    A p-chain is a fundamental object in simplicial homology, representing a
    linear combination of p-dimensional simplices. This class supports addition,
    subtraction, scalar multiplication, and negation.

    Zero-coefficient terms are automatically removed to maintain a canonical
    sparse representation.

    .. rubric:: Parameters

    keys : list
        A list of p-simplices (typically tuples).
    values : list
        A list of integer coefficients for each simplex.

    .. rubric:: Examples

    Creating a p-chain with two 2-simplices::

        >>> from pyhomrep.pchains import PChain
        >>> p = PChain([(0, 1, 2), (0, 1, 3)], [-1, 2])
        >>> p
        {(0, 1, 2): -1, (0, 1, 3): 2}

    Adding two p-chains::

        >>> p1 = PChain([(0, 1, 2)], [2])
        >>> p2 = PChain([(0, 1, 3)], [5])
        >>> (p1 + p2).dic
        {(0, 1, 2): 2, (0, 1, 3): 5}

    Scalar multiplication::

        >>> p = PChain([(7, 8, 9), (10, 11, 12)], [3, 2])
        >>> (3 * p).dic
        {(7, 8, 9): 9, (10, 11, 12): 6}

    Negation::

        >>> p = PChain([(0, 1)], [3])
        >>> (-p).dic
        {(0, 1): -3}
    """

    def __init__(self, keys: list, values: list, *, _filter_zeros: bool = True) -> None:
        """Initialize a p-chain.

        .. rubric:: Parameters

        keys : list
            A list of p-simplices (typically tuples).
        values : list
            A list of integer coefficients for each simplex.
        _filter_zeros : bool, optional
            If True (default), remove zero-coefficient terms.

        .. rubric:: Raises

        IndexError
            If the number of simplices does not match the number of coefficients.
        TypeError
            If the simplices given are not immutable data types like tuples.
        """
        if _filter_zeros:
            # Filter out zero coefficients for canonical representation
            self.dic: dict[Any, int] = {k: v for k, v in zip(keys, values) if v != 0}
        else:
            self.dic = dict(zip(keys, values))
        self.keys = list(self.dic.keys())
        self.values = list(self.dic.values())

    def __repr__(self) -> str:
        """Return a string representation of the p-chain."""
        return str(self.dic)

    def __add__(self, other: PChain) -> PChain:
        """Add two p-chains.

        .. rubric:: Parameters

        other : PChain
            Another p-chain to add.

        .. rubric:: Returns

        PChain
            A new p-chain that is the sum of the two p-chains.

        .. rubric:: Examples

        >>> from pyhomrep.pchains import PChain
        >>> p1 = PChain([(0, 1, 2)], [2])
        >>> p2 = PChain([(0, 1, 3)], [5])
        >>> result = p1 + p2
        >>> result.dic
        {(0, 1, 2): 2, (0, 1, 3): 5}

        When simplices overlap with cancellation, zeros are removed::

            >>> p1 = PChain([(0, 1, 2)], [2])
            >>> p2 = PChain([(0, 1, 2)], [-2])
            >>> (p1 + p2).dic
            {}
        """
        d: dict[Any, int] = dict(self.dic)
        for simplex, coeff in other.dic.items():
            d[simplex] = d.get(simplex, 0) + coeff
        return PChain(list(d.keys()), list(d.values()))

    def __sub__(self, other: PChain) -> PChain:
        """Subtract two p-chains.

        .. rubric:: Parameters

        other : PChain
            The p-chain to subtract.

        .. rubric:: Returns

        PChain
            A new p-chain that is the difference of the two p-chains.

        .. rubric:: Examples

        >>> from pyhomrep.pchains import PChain
        >>> p1 = PChain([(3, 4, 5)], [3])
        >>> p2 = PChain([(1, 8, 9)], [1])
        >>> (p1 - p2).dic
        {(3, 4, 5): 3, (1, 8, 9): -1}
        """
        d: dict[Any, int] = dict(self.dic)
        for simplex, coeff in other.dic.items():
            d[simplex] = d.get(simplex, 0) - coeff
        return PChain(list(d.keys()), list(d.values()))

    def __neg__(self) -> PChain:
        """Negate a p-chain.

        .. rubric:: Returns

        PChain
            A new p-chain with all coefficients negated.

        .. rubric:: Examples

        >>> from pyhomrep.pchains import PChain
        >>> p = PChain([(0, 1, 2)], [3])
        >>> (-p).dic
        {(0, 1, 2): -3}
        """
        return PChain(self.keys, [-v for v in self.values])

    def __eq__(self, other: object) -> bool:
        """Check if two p-chains are equal.

        .. rubric:: Parameters

        other : PChain
            Another p-chain to compare.

        .. rubric:: Returns

        bool
            True if the p-chains have identical simplices and coefficients.

        .. rubric:: Examples

        >>> from pyhomrep.pchains import PChain
        >>> p1 = PChain([(0, 1, 2), (3, 4, 5)], [1, 1])
        >>> p2 = PChain([(3, 4, 5), (0, 1, 2)], [1, 1])
        >>> p1 == p2
        True
        """
        if not isinstance(other, PChain):
            return NotImplemented
        return self.dic == other.dic

    def __ne__(self, other: object) -> bool:
        """Check if two p-chains are not equal.

        .. rubric:: Parameters

        other : PChain
            Another p-chain to compare.

        .. rubric:: Returns

        bool
            True if the p-chains differ.

        .. rubric:: Examples

        >>> from pyhomrep.pchains import PChain
        >>> p1 = PChain([(0, 1, 2, 4)], [1])
        >>> p2 = PChain([(0, 1, 4, 2)], [-2])
        >>> p1 != p2
        True
        """
        return not self.__eq__(other)

    def __rmul__(self, other: int) -> PChain:
        """Multiply a p-chain by a scalar (right multiplication: scalar * chain).

        .. rubric:: Parameters

        other : int
            The scalar to multiply by.

        .. rubric:: Returns

        PChain
            A new p-chain with coefficients scaled by the scalar.

        .. rubric:: Examples

        >>> from pyhomrep.pchains import PChain
        >>> p = PChain([(7, 8, 9), (10, 11, 12)], [3, 2])
        >>> (3 * p).dic
        {(7, 8, 9): 9, (10, 11, 12): 6}
        >>> q = PChain([(0, 1, 4, 2, 6)], [-5])
        >>> ((-1) * q).dic
        {(0, 1, 4, 2, 6): 5}
        """
        return PChain(self.keys, [other * v for v in self.values])

    def __mul__(self, other: int) -> PChain:
        """Multiply a p-chain by a scalar (left multiplication: chain * scalar).

        .. rubric:: Parameters

        other : int
            The scalar to multiply by.

        .. rubric:: Returns

        PChain
            A new p-chain with coefficients scaled by the scalar.

        .. rubric:: Examples

        >>> from pyhomrep.pchains import PChain
        >>> p = PChain([(0, 1, 2)], [4])
        >>> (p * 2).dic
        {(0, 1, 2): 8}
        """
        return PChain(self.keys, [other * v for v in self.values])

    def __hash__(self) -> int:
        """Return the hash of the p-chain.

        P-chains are hashable based on their simplex-coefficient pairs,
        allowing them to be used as dictionary keys or in sets.

        .. rubric:: Returns

        int
            The hash value.

        .. rubric:: Examples

        >>> from pyhomrep.pchains import PChain
        >>> p1 = PChain([(0, 1, 2)], [1])
        >>> p2 = PChain([(0, 1, 2)], [1])
        >>> hash(p1) == hash(p2)
        True
        >>> {p1, p2}  # Can be used in sets
        {{(0, 1, 2): 1}}
        """
        return hash(frozenset(self.dic.items()))

    def is_zero(self) -> bool:
        """Check if this p-chain is the zero chain.

        .. rubric:: Returns

        bool
            True if all coefficients are zero (or the chain is empty).

        .. rubric:: Examples

        >>> from pyhomrep.pchains import PChain
        >>> PChain([], []).is_zero()
        True
        >>> PChain([(0, 1)], [0]).is_zero()
        True
        >>> PChain([(0, 1)], [1]).is_zero()
        False
        """
        return len(self.dic) == 0
