"""Simplicial complex functions for representation theory.

This module provides functions for computing representations on homology groups
of simplicial complexes, with a focus on actions of symmetric groups.

Mathematical Background
-----------------------
Given a simplicial complex K with an action of a group G, the group acts on
the chain groups C_p(K). This induces a representation of G on the homology
groups H_p(K). The character of this representation can be computed via the
Lefschetz fixed-point theorem.

For the symmetric group S_n acting on a complex K, the decomposition of the
representation on H_p(K) into irreducibles can be computed using the
Murnaghan-Nakayama rule and character theory.

References
----------
- Friedman, J. "Computing Betti numbers via combinatorial Laplacians"
- Fulton, W. & Harris, J. "Representation Theory: A First Course"
- Sagan, B. "The Symmetric Group: Representations, Combinatorial Algorithms,
  and Symmetric Functions"
"""

from __future__ import annotations

import math
from typing import TYPE_CHECKING, Any

import numpy as np
from pycombtop import SimplicialComplex
from sympy import eye
from sympy.matrices import Matrix, zeros
from sympy.solvers.solveset import linsolve

from pyhomrep.pchains import PChain
from pyhomrep.utilities import (
    boundary_op_n,
    columnspace,
    form_matrix_yt,
    have_same_elements,
    make_permutation,
    nullspace,
    orientation_function,
    partitions_list,
    permutation_in_simplex_test,
    reduce_matrix,
    size_conjugacy_class,
)

if TYPE_CHECKING:
    from sympy.combinatorics import Permutation


def faces(sc: SimplicialComplex) -> list[tuple]:
    """Return all faces of the simplicial complex, sorted by dimension.

    .. rubric:: Parameters

    sc : SimplicialComplex
        The simplicial complex.

    .. rubric:: Returns

    list
        A list of faces (as tuples), sorted by increasing dimension.

    .. rubric:: Examples

    >>> from pycombtop import clique_complex
    >>> import networkx as nx
    >>> from pyhomrep.simplicial import faces
    >>> sc = clique_complex(nx.complete_graph(3))
    >>> faces(sc)
    [(), (0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)]
    """
    all_simp = sc.all_simplices()
    return sorted([tuple(sorted(s)) for s in all_simp], key=lambda x: (len(x), x))


def p_simplex(sc: SimplicialComplex, p: int) -> list[tuple]:
    """Return all p-dimensional simplices.

    .. rubric:: Parameters

    sc : SimplicialComplex
        The simplicial complex.
    p : int
        The dimension.

    .. rubric:: Returns

    list
        A list of p-simplices (as tuples).

    .. rubric:: Examples

    >>> from pycombtop import clique_complex
    >>> import networkx as nx
    >>> from pyhomrep.simplicial import p_simplex
    >>> sc = clique_complex(nx.complete_graph(3))
    >>> p_simplex(sc, 0)
    [(0,), (1,), (2,)]
    >>> p_simplex(sc, 1)
    [(0, 1), (0, 2), (1, 2)]
    >>> p_simplex(sc, 2)
    [(0, 1, 2)]
    >>> p_simplex(sc, 5)
    []
    """
    return [face for face in faces(sc) if len(face) == p + 1]


def basis_group_oriented_p_chains(sc: SimplicialComplex, p: int) -> PChain | None:
    """Return a basis for the group of oriented p-chains C_p(K).

    The group of oriented p-chains is the free abelian group generated by
    oriented p-simplices. This function returns a PChain with coefficient 1
    for each p-simplex, representing the standard basis.

    .. rubric:: Parameters

    sc : SimplicialComplex
        The simplicial complex.
    p : int
        The dimension.

    .. rubric:: Returns

    PChain or None
        A p-chain representing the basis, or None if p is out of range.

    .. rubric:: Examples

    >>> from pycombtop import clique_complex
    >>> import networkx as nx
    >>> from pyhomrep.simplicial import basis_group_oriented_p_chains
    >>> from pyhomrep.graphs import matching_graph
    >>> G = matching_graph(3)
    >>> sc = clique_complex(G)
    >>> basis_group_oriented_p_chains(sc, 0).dic
    {((0, 1),): 1, ((0, 2),): 1, ((1, 2),): 1}
    """
    dim = sc.dimension()
    if (p < 0) or (p > dim):
        return None
    simplices = p_simplex(sc, p)
    if not simplices:
        return None
    c_p = PChain([], [])
    for x in simplices:
        c_p = c_p + PChain([tuple(sorted(x))], [1])
    return c_p


def representate_in_simplex(
    sc: SimplicialComplex, vec: PChain, perm: Permutation
) -> PChain:
    """Apply a permutation to a p-chain in this simplicial complex.

    .. rubric:: Parameters

    sc : SimplicialComplex
        The simplicial complex.
    vec : PChain
        The p-chain to transform.
    perm : Permutation
        The permutation to apply.

    .. rubric:: Returns

    PChain
        The transformed p-chain.
    """
    from pyhomrep.utilities import tuple_permutation

    s = PChain([], [])
    if not vec.dic:
        return s

    keys = list(vec.dic.keys())
    p_dim = len(keys[0]) - 1
    ve = basis_group_oriented_p_chains(sc, p_dim)
    if ve is None:
        return s

    for a in keys:
        if isinstance(a, int):
            return vec
        w = tuple_permutation(a, perm)
        for b in ve.dic:
            if have_same_elements(b, w):
                if orientation_function(b, w, p_dim):
                    s = s + PChain([b], [vec.dic[a]])
                else:
                    s = s - PChain([b], [vec.dic[a]])
    return s


def matrix_symmetric_representate(sc: SimplicialComplex, p: int) -> Matrix | None:
    """Return the matrix of the boundary operator d_p: C_p -> C_{p-1}.

    The boundary operator is represented as a matrix with respect to the
    standard bases of C_p and C_{p-1}.

    .. rubric:: Parameters

    sc : SimplicialComplex
        The simplicial complex.
    p : int
        The dimension.

    .. rubric:: Returns

    Matrix or None
        The boundary matrix, or None if p is out of range.

    .. rubric:: Examples

    >>> from pycombtop import clique_complex
    >>> import networkx as nx
    >>> from pyhomrep.simplicial import matrix_symmetric_representate
    >>> from pyhomrep.graphs import matching_graph
    >>> G = matching_graph(3)
    >>> sc = clique_complex(G)
    >>> matrix_symmetric_representate(sc, 0)
    Matrix([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]])
    """
    dim = sc.dimension()
    if p > 0 and (p <= dim):
        v = basis_group_oriented_p_chains(sc, p)
        if v is None:
            return None
        p_dim = p - 1
        ve = basis_group_oriented_p_chains(sc, p_dim)
        if ve is None:
            return None
        M = zeros(len(ve.dic), len(v.dic))
        v_keys = list(v.dic.keys())
        ve_keys = list(ve.dic.keys())
        for j, u1 in enumerate(v_keys):
            d = PChain([u1], [v.dic[u1]])
            boundary = boundary_op_n(d)
            for u2, coeff in boundary.dic.items():
                for i, w in enumerate(ve_keys):
                    if w == u2:
                        M[i, j] = int(coeff)
        return M
    elif p == 0:
        basisg = basis_group_oriented_p_chains(sc, 0)
        if basisg is None:
            return None
        return eye(len(basisg.dic))
    else:
        return None
        if p == 0:
            basisg = basis_group_oriented_p_chains(sc, 0)
            if basisg == 0:
                return False
            return eye(len(list(basisg.dic.keys())))
        else:
            return False


def kernel_boundary_op(sc: SimplicialComplex, p: int) -> list[PChain] | None:
    """Compute a basis for the kernel of the boundary operator (cycles).

    The kernel ker(d_p) in C_p(K) is the group of p-cycles Z_p(K).

    .. rubric:: Parameters

    sc : SimplicialComplex
        The simplicial complex.
    p : int
        The dimension.

    .. rubric:: Returns

    list or None
        A list of p-chains spanning the kernel, or None if undefined.
    """
    dim = sc.dimension()
    if (p > 0) and (p <= dim):
        M = matrix_symmetric_representate(sc, p)
        if M is None:
            return None
        u = nullspace(M)
        # Check if nullspace is trivial (only zero vector)
        if u and any(any(x != 0 for x in vec) for vec in u):
            v = basis_group_oriented_p_chains(sc, p)
            if v is None:
                return None
            v_keys = list(v.dic.keys())
            result: list[PChain] = []
            for vec in u:
                s = PChain([], [])
                for j, coeff in enumerate(vec):
                    if coeff != 0:
                        s = s + PChain([v_keys[j]], [coeff])
                result.append(s)
            return result
        return None
    elif p == 0:
        basis = basis_group_oriented_p_chains(sc, p)
        if basis is None:
            return None
        return [basis]
    else:
        return None


def image_boundary_op(sc: SimplicialComplex, p: int) -> list[PChain] | None:
    """Compute a basis for the image of the boundary operator (boundaries).

    The image im(d_p) in C_{p-1}(K) is the group of (p-1)-boundaries B_{p-1}(K).

    .. rubric:: Parameters

    sc : SimplicialComplex
        The simplicial complex.
    p : int
        The dimension.

    .. rubric:: Returns

    list or None
        A list of (p-1)-chains spanning the image, or None if undefined.
    """
    dim = sc.dimension()
    if (p > 0) and (p <= dim):
        M = matrix_symmetric_representate(sc, p)
        if M is None:
            return None
        u = columnspace(M)
        # Check if columnspace is trivial (only zero vector)
        if u and any(any(x != 0 for x in vec) for vec in u):
            v = basis_group_oriented_p_chains(sc, p - 1)
            if v is None:
                return None
            v_keys = list(v.dic.keys())
            result: list[PChain] = []
            for vec in u:
                s = PChain([], [])
                for j, coeff in enumerate(vec):
                    if coeff != 0:
                        s = s + PChain([v_keys[j]], [coeff])
                result.append(s)
            return result
        return None
    else:
        return None


def character_kernel(sc: SimplicialComplex, p: int, perm: Permutation) -> Any:
    """Compute the character of a permutation on the kernel.

    .. rubric:: Parameters

    sc : SimplicialComplex
        The simplicial complex.
    p : int
        The dimension.
    perm : Permutation
        The permutation.

    .. rubric:: Returns

    int
        The character value (trace).

    .. rubric:: Examples

    >>> from pycombtop import clique_complex
    >>> import networkx as nx
    >>> from pyhomrep.simplicial import character_kernel
    >>> from pyhomrep.graphs import matching_graph
    >>> from sympy.combinatorics import Permutation
    >>> G = matching_graph(4)
    >>> sc = clique_complex(G)
    >>> character_kernel(sc, 0, Permutation())
    6
    """
    dim = sc.dimension()
    M = matrix_symmetric_representate(sc, p)
    if M is None:
        return 0
    if p > 0 and (p <= dim):
        null = nullspace(M)
        M_mat: list[list] = [
            [null[j][i] for j in range(len(null))] for i in range(len(null[0]))
        ]
        Q = reduce_matrix(Matrix(M_mat))
        M_work = Q[0] * Matrix(M_mat)
    elif p == 0:
        M_work = M
        null = [[M_work[i, j] for j in range(M.shape[1])] for i in range(M.shape[0])]
        Q = reduce_matrix(Matrix(M_work))
        M_work = Q[0] * Matrix(M_work)
    else:
        return 0

    if all(elem == null[0][0] for elem in null[0]):
        return 0

    w1: list = []
    he = basis_group_oriented_p_chains(sc, p)
    if he is None:
        return 0
    for a in range(len(null)):
        v = PChain([], [])
        c = 0
        for j in list(he.dic.keys()):
            v = v + PChain([j], [null[a][c]])
            c = c + 1
        v1 = permutation_in_simplex_test(v, perm)
        u: list = []
        for i in he.dic.keys():
            u.append(np.array([v1.dic.get(i, 0)]))
        u_mat = Q[0] * Matrix(u)
        N = np.append(M_work, u_mat, axis=1)
        N = Matrix(N)
        w2: list = []
        for i in tuple(linsolve(N)):
            for j in i:
                w2.append(j)
        w1.append(w2)
    N = Matrix(w1)
    return np.trace(N.T)


def character_image(sc: SimplicialComplex, p: int, perm: Permutation) -> Any:
    """Compute the character of a permutation on the image.

    .. rubric:: Parameters

    sc : SimplicialComplex
        The simplicial complex.
    p : int
        The dimension.
    perm : Permutation
        The permutation.

    .. rubric:: Returns

    int
        The character value (trace).

    .. rubric:: Examples

    >>> from pycombtop import clique_complex
    >>> import networkx as nx
    >>> from pyhomrep.simplicial import character_image
    >>> from pyhomrep.graphs import matching_graph
    >>> from sympy.combinatorics import Permutation
    >>> G = matching_graph(5)
    >>> sc = clique_complex(G)
    >>> character_image(sc, 1, Permutation(0, 1))
    3
    >>> character_image(sc, 1, Permutation())
    9
    """
    dim = sc.dimension()
    if p > 0 and (p <= dim):
        M = matrix_symmetric_representate(sc, p)
        if M is None:
            return 0
        w1: list = []
        col = columnspace(M)
        M_mat: list[list] = [
            [col[j][i] for j in range(len(col))] for i in range(len(col[0]))
        ]
        Q = reduce_matrix(Matrix(M_mat))
        M_work = Q[0] * Matrix(M_mat)
        he = basis_group_oriented_p_chains(sc, p - 1)
        if he is None:
            return 0
        for a in range(len(col)):
            v = PChain([], [])
            c = 0
            for j in list(he.dic.keys()):
                v = v + PChain([j], [col[a][c]])
                c = c + 1
            v1 = permutation_in_simplex_test(v, perm)
            u: list = []
            for i in he.dic.keys():
                u.append(np.array([v1.dic.get(i, 0)]))
            u_mat = Q[0] * Matrix(u)
            N = np.append(M_work, u_mat, axis=1)
            N = Matrix(N)
            w2: list = []
            for i in tuple(linsolve(N)):
                for j in i:
                    w2.append(j)
            w1.append(w2)
        N = Matrix(w1)
        return np.trace(N.T)
    else:
        return 0


def character_p_homology(sc: SimplicialComplex, p: int, perm: Permutation) -> Any:
    """Compute the character of a permutation on the p-th homology.

    .. rubric:: Parameters

    sc : SimplicialComplex
        The simplicial complex.
    p : int
        The dimension.
    perm : Permutation
        The permutation.

    .. rubric:: Returns

    int
        The character value (trace).

    .. rubric:: Examples

    >>> from pycombtop import clique_complex
    >>> import networkx as nx
    >>> from pyhomrep.simplicial import character_p_homology
    >>> from pyhomrep.graphs import matching_graph
    >>> from sympy.combinatorics import Permutation
    >>> G = matching_graph(5)
    >>> sc = clique_complex(G)
    >>> character_p_homology(sc, 0, Permutation())
    1
    """
    return character_kernel(sc, p, perm) - character_image(sc, p + 1, perm)


def decompose_into_irreducibles(
    sc: SimplicialComplex, n: int
) -> dict[int, dict[tuple, Any]]:
    """Decompose the homology representation into irreducible S_n-representations.

    Given an action of S_n on a simplicial complex K, the homology groups
    H_p(K) become S_n-modules. This function computes the multiplicities of
    each irreducible S_n-representation (indexed by partitions of n) in each
    H_p(K).

    .. rubric:: Parameters

    sc : SimplicialComplex
        The simplicial complex with an S_n action.
    n : int
        The size of the symmetric group S_n.

    .. rubric:: Returns

    dict
        A dictionary mapping dimensions p to dictionaries of irreducible
        multiplicities indexed by partitions of n.

    .. rubric:: Examples

    >>> from pycombtop import clique_complex
    >>> from pyhomrep.simplicial import decompose_into_irreducibles
    >>> from pyhomrep.graphs import matching_graph
    >>> n = 4
    >>> G1 = matching_graph(n)
    >>> sc1 = clique_complex(G1)
    >>> result = decompose_into_irreducibles(sc1, n)
    >>> result[0][(4,)]  # Multiplicity of trivial representation in H_0
    1
    >>> result[0][(2, 2)]  # Multiplicity of representation indexed by (2,2)
    1
    """
    w = partitions_list(n)
    M = form_matrix_yt(w)
    card = math.factorial(n)
    dim = sc.dimension()
    vec_dic: dict[int, dict[tuple, Any]] = {}
    for k in range(dim + 1):
        D: dict[tuple, Any] = {}
        u: list = []
        v: list = []
        for h in w:
            u.append(character_p_homology(sc, k, make_permutation(h)))
            v.append(size_conjugacy_class(h, n))
        for i in range(M.shape[0]):
            Ip = 0
            for j in range(M.shape[1]):
                Ip = Ip + M[i, j] * u[j] * v[j]
            Ip = Ip / card
            D[tuple(w[i])] = Ip
        vec_dic[k] = D
    return vec_dic


def character_matrix_permutation(
    sc: SimplicialComplex, p: int, perm: Permutation
) -> Any:
    """Compute character via the matrix of the permutation action.

    .. rubric:: Parameters

    sc : SimplicialComplex
        The simplicial complex.
    p : int
        The dimension.
    perm : Permutation
        The permutation.

    .. rubric:: Returns

    int
        The character value (trace).
    """
    v = basis_group_oriented_p_chains(sc, p)
    if v is None:
        return 0
    v1 = permutation_in_simplex_test(v, perm)
    n = len(v.dic)
    M = zeros(n, n)
    v_keys = list(v.dic.keys())
    for i, u1 in enumerate(v_keys):
        for j, u2 in enumerate(v1.dic.keys()):
            if u1 == u2:
                M[i, j] = v1.dic[u2]
    return np.trace(M)
