"""Public package exports for the pycliques project."""

__version__ = "0.1.0"

from .cliques import Clique, NodeH, clique_graph, homotopy_clique_graph
from .clockwork import (
    ClockworkGraph,
    ClockworkStructure,
    clockwork_graph,
    core,
    crown,
    crown_general,
    has_induced_4cycle,
    is_clique_divergent_clockwork,
    is_complete_graph,
    recognize_as_clockwork_graph,
    recognize_clockwork,
    remove_dominated_vertices,
    segmented_sum,
)
from .coaffinations import (
    CoaffinePair,
    automorphisms,
    coaffinations,
    coaffine_monomorphism,
    is_coaffine_map,
)
from .cutpoints import (
    contract_local_bridge,
    edge_in_triangle,
    edges_in_no_triangle,
    is_local_bridge,
    local_bridge_contractions,
    local_bridges,
    non_triangle_edge_removals,
    remove_edge_not_in_triangle,
)
from .dominated import (
    closed_neighborhood,
    completely_pared_graph,
    dominates,
    find_dominated_vertex,
    is_dismantlable,
    is_dominated_vertex,
    pared_graph,
    pared_index,
    remove_dominated_vertex,
    twin_classes,
)
from .helly import (
    is_clique_helly,
    is_hereditary_clique_helly,
    n_closed,
    n_open,
    u_closed,
    u_open,
)
from .homotopy_invariance import (
    completes_of_size,
    completes_with_empty_intersection,
    delta_of_clique_set,
    discrete_morse_matching,
    h_closure,
    has_center_at_all,
    is_center,
    minimal_violation,
    neckties,
    theorem11_hypothesis_holds,
    theorem15_hypothesis_holds,
    verify_discrete_morse_matching,
    witnesses_and_extension,
)
from .named import (
    collapse_obstruction_fixture,
    complement_of_cycle,
    dominated_vertex_free_non_helly,
    graph_suspension,
    octahedron,
    snub_disphenoid,
    suspension_of_cycle,
)
from .retractions import (
    dict_to_tuple,
    graph_from_gap_adjacency_list,
    has_induced,
    invert_dict,
    is_map,
    is_O3_free,
    retraction,
    retracts,
    retracts_to,
    special_octahedra,
    special_octahedra_dimension,
)
from .small import (
    Certificate,
    CliqueBehavior,
    CliqueSequence,
    ReferenceStatus,
    Verdict,
    classify_clique_behavior,
    classify_local_bridge,
    classify_non_triangle_edge,
    clear_reference_graphs,
    eventually_retracts_specially,
    is_eventually_helly,
    register_reference_graph,
)
from .surfaces import (
    is_closed_surface,
    is_cycle,
    is_path,
    is_regular,
    is_surface,
    open_neighborhood,
)

__all__ = [
    "__version__",
    # cliques
    "Clique",
    "NodeH",
    "clique_graph",
    "homotopy_clique_graph",
    # clockwork
    "ClockworkGraph",
    "ClockworkStructure",
    "clockwork_graph",
    "core",
    "crown",
    "crown_general",
    "has_induced_4cycle",
    "is_clique_divergent_clockwork",
    "is_complete_graph",
    "recognize_as_clockwork_graph",
    "recognize_clockwork",
    "remove_dominated_vertices",
    "segmented_sum",
    # coaffinations
    "CoaffinePair",
    "automorphisms",
    "coaffinations",
    "coaffine_monomorphism",
    "is_coaffine_map",
    # cutpoints
    "contract_local_bridge",
    "edge_in_triangle",
    "edges_in_no_triangle",
    "is_local_bridge",
    "local_bridge_contractions",
    "local_bridges",
    "non_triangle_edge_removals",
    "remove_edge_not_in_triangle",
    # dominated
    "closed_neighborhood",
    "completely_pared_graph",
    "dominates",
    "find_dominated_vertex",
    "is_dismantlable",
    "is_dominated_vertex",
    "pared_graph",
    "pared_index",
    "remove_dominated_vertex",
    "twin_classes",
    # helly
    "is_clique_helly",
    "is_hereditary_clique_helly",
    "n_closed",
    "n_open",
    "u_closed",
    "u_open",
    # homotopy_invariance
    "completes_of_size",
    "completes_with_empty_intersection",
    "delta_of_clique_set",
    "discrete_morse_matching",
    "h_closure",
    "has_center_at_all",
    "is_center",
    "minimal_violation",
    "neckties",
    "theorem11_hypothesis_holds",
    "theorem15_hypothesis_holds",
    "verify_discrete_morse_matching",
    "witnesses_and_extension",
    # named
    "collapse_obstruction_fixture",
    "complement_of_cycle",
    "dominated_vertex_free_non_helly",
    "graph_suspension",
    "octahedron",
    "snub_disphenoid",
    "suspension_of_cycle",
    # retractions
    "dict_to_tuple",
    "graph_from_gap_adjacency_list",
    "has_induced",
    "invert_dict",
    "is_O3_free",
    "is_map",
    "retraction",
    "retracts",
    "retracts_to",
    "special_octahedra",
    "special_octahedra_dimension",
    # small
    "Certificate",
    "CliqueBehavior",
    "CliqueSequence",
    "ReferenceStatus",
    "Verdict",
    "classify_clique_behavior",
    "classify_local_bridge",
    "classify_non_triangle_edge",
    "clear_reference_graphs",
    "eventually_retracts_specially",
    "is_eventually_helly",
    "register_reference_graph",
    # surfaces
    "is_closed_surface",
    "is_cycle",
    "is_path",
    "is_regular",
    "is_surface",
    "open_neighborhood",
]
